version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: inatel_teste_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inatelDB
      MYSQL_USER: defaultUser
      MYSQL_PASSWORD: defaultPassword
    ports:
      - "3306:3306"
    # networks:
    #   - backend
    volumes:
      - mysql-data:/var/lib/mysql

  myapp:
    build:
      context: ./InatelTeste.API
    container_name: inatel_teste_api
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_URLS=http://+:5000
    #   - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=my_database;User=root;Password=rootpassword;
    ports:
      - "5000:5000"
    command: >
      sh -c "
        wait-for-it mysql:3306 --timeout=60 -- echo 'MySQL is up!';
        dotnet ef database update --project InatelTeste.Infrastructure/InatelTeste.Infrastructure.csproj --startup-project InatelTeste.API/InatelTeste.API.csproj &&
        dotnet YourApiProject.dll"
    # networks:
    #   - backend

# networks:
#   backend:
#     driver: bridge

volumes:
  mysql-data:
    driver: local