version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: inatel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inatelDB
      MYSQL_USER: defaultUser
      MYSQL_PASSWORD: defaultPassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build:
      context: ./InatelTeste.API
    container_name: inatel_api
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Default=Server=mysql;Port=3306;Database=inatelDB;User=root;Password=rootpassword;
    ports:
      - "5000:5000"

  angular-app:
    build:
      context: ./InatelTeste.Client
    container_name: inatel_client
    ports:
      - "4200:4200"

volumes:
  mysql-data:
    driver: local