// <auto-generated />
using InatelTeste.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InatelTeste.Infrastructure.migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241117223503_addPropertiesInUniversityTable")]
    partial class addPropertiesInUniversityTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InatelTeste.Domain.Entities.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Domain");
                });

            modelBuilder.Entity("InatelTeste.Domain.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StateProvince")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("University");
                });

            modelBuilder.Entity("InatelTeste.Domain.Entities.WebPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("WebPage");
                });

            modelBuilder.Entity("InatelTeste.Domain.Entities.Domain", b =>
                {
                    b.HasOne("InatelTeste.Domain.Entities.University", "University")
                        .WithMany("Domains")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("InatelTeste.Domain.Entities.WebPage", b =>
                {
                    b.HasOne("InatelTeste.Domain.Entities.University", "University")
                        .WithMany("WebPages")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("InatelTeste.Domain.Entities.University", b =>
                {
                    b.Navigation("Domains");

                    b.Navigation("WebPages");
                });
#pragma warning restore 612, 618
        }
    }
}
